# Generated by Django 3.0.4 on 2020-05-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostedApis', '0002_songcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EachSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('songUrl', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=20)),
            ],
        ),
    ]
