# Generated by Django 3.0.4 on 2020-05-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostedApis', '0003_eachsong'),
    ]

    operations = [
        migrations.AddField(
            model_name='eachsong',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
    ]
